server:
  port: 8087
spring:
  application:
    name: auth-service
  main:
    allow-bean-definition-overriding: true  # 配置可以重名
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka
    registry-fetch-interval-seconds: 10
  instance:
    lease-renewal-interval-in-seconds: 5  # 每隔5秒发送一次心跳
    lease-expiration-duration-in-seconds: 15  # 10秒不发送就过期
    prefer-ip-address: true
    ip-address: 127.0.0.1
ly:
  jwt:
    secret: ly@Login(Auth}*^31)&heiMa% # 登录校验的密钥
    pubKeyPath: F:\test\rsa\rsa.pub # 公钥地址
    priKeyPath: F:\test\rsa\rsa.pri # 私钥地址
    expire: 30 # 过期时间,单位分钟
    cookieName: LY_TOKEN