server:
  port: 10086

spring:
  application:
    name: leyou-registry
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka
    fetch-registry: false  # 不拉取服务列表
    register-with-eureka: false  # 不将自己注册到eureka服务器
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 10000