server:
  port: 8086
spring:
  application:
    name: sms-service
  rabbitmq:
    host: 192.168.150.128
    username: leyou
    password: leyou
    virtual-host: /leyou
ly:
  sms:
    accessKeyId: LTAI4G64W3rjjbnh3Asu61WH # 你自己的accessKeyId
    accessKeySecret: brCpYgdV4y1SpgIr10v62Kkjjx89CF # 你自己的AccessKeySecret
    signName: 乐优商城 # 签名名称
    verifyCodeTemplate: SMS_188991470 # 模板名称